# replacements = 'github.com/shoginn/wowchemy-block-countdown-timer -> ../../wowchemy-block-countdown-timer,github.com/shoginn/wowchemy-block-instagram-behold/v3 -> ../../wowchemy-block-instagram-behold,github.com/shoginn/wowchemy-block-pricing-cards -> ../../wowchemy-block-pricing-cards'
[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/shoginn/wowchemy-block-pricing-cards"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/shoginn/wowchemy-block-instagram-behold/v3"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/shoginn/wowchemy-block-countdown-timer"
