---
name: Update GoHugo version for Netlify
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: Update GoHugo version for Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ${GITHUB_WORKSPACE}/bin/netlify/update-hugo-version.sh > "${GITHUB_WORKSPACE}/netlify.toml"
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(config): update Netlify configuration'
          committer: Scott <2660603+ShoGinn@users.noreply.github.com>
          author: Scott <2660603+ShoGinn@users.noreply.github.com>
          signoff: true
          branch: config/netlify
          delete-branch: true
          title: 'chore(config): update GoHugo version in netlify.toml'
          body: Update netlify.toml with current latest GoHugo version number
          assignees: ShoGinn
          reviewers: ShoGinn
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"
